# Generated by Django 5.1.6 on 2025-02-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUserModel',
            fields=[
                ('social_media_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts_connection.socialmediaaccount')),
                ('facebook_user_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('facebook_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('facebook_user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_user_access_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
