# Generated by Django 5.1.6 on 2025-02-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_connection', '0001_initial'),
        ('platform_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramModel',
            fields=[
                ('social_media_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts_connection.socialmediaaccount')),
                ('instagram_id', models.CharField(max_length=255)),
                ('instagram_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_access_token', models.CharField(max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('followers_count', models.BigIntegerField(blank=True, null=True)),
                ('following_count', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPageModel',
            fields=[
                ('social_media_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts_connection.socialmediaaccount')),
                ('facebook_page_id', models.CharField(max_length=255)),
                ('facebook_page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('global_name_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_page_access_token', models.CharField(max_length=255)),
                ('facebook_page_picture_url', models.TextField(blank=True, null=True)),
                ('followers_count', models.BigIntegerField(blank=True, null=True)),
                ('following_count', models.BigIntegerField(blank=True, null=True)),
                ('tasks', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('facebook_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_media.facebookusermodel')),
            ],
        ),
    ]
