# Generated by Django 5.1.1 on 2025-03-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='external_account_id',
            field=models.CharField(max_length=255),
        ),
    ]
